container:
  image: debian:latest

task:
  kernel_cache:
    folder: linux
    fingerprint_key: linux
  retrieve_script:
    - apt-get update && apt-get -y install git
    - git clone https://github.com/torvalds/linux.git
